/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as PublicRouteImport } from './routes/_public';
import { Route as PrivateRouteImport } from './routes/_private';
import { Route as PrivateIndexRouteImport } from './routes/_private/index';
import { Route as PublicPrivacyPolicyIndexRouteImport } from './routes/_public/privacy-policy/index';
import { Route as PublicNewAccessIndexRouteImport } from './routes/_public/new-access/index';
import { Route as PublicForgotPasswordIndexRouteImport } from './routes/_public/forgot-password/index';
import { Route as PublicDevelopIndexRouteImport } from './routes/_public/develop/index';
import { Route as PublicContactIndexRouteImport } from './routes/_public/contact/index';
import { Route as PublicAppAuthIndexRouteImport } from './routes/_public/app-auth/index';
import { Route as PrivateVisitorsIndexRouteImport } from './routes/_private/visitors/index';
import { Route as PrivateUnitsIndexRouteImport } from './routes/_private/units/index';
import { Route as PrivateSyncStatusIndexRouteImport } from './routes/_private/sync-status/index';
import { Route as PrivateServiceProvidersIndexRouteImport } from './routes/_private/service-providers/index';
import { Route as PrivateReservationsIndexRouteImport } from './routes/_private/reservations/index';
import { Route as PrivateDependentsIndexRouteImport } from './routes/_private/dependents/index';
import { Route as PrivateAccessUserIndexRouteImport } from './routes/_private/access-user/index';
import { Route as PublicNewUserIdRouteImport } from './routes/_public/new-user/$id';
import { Route as PrivateReservationsDetailsRouteImport } from './routes/_private/reservations/details';
import { Route as PublicAccomplishAccessIdIndexRouteImport } from './routes/_public/accomplish-access/$id/index';
import { Route as PrivateVisitorsAddIndexRouteImport } from './routes/_private/visitors/add/index';
import { Route as PrivateServiceProvidersAddIndexRouteImport } from './routes/_private/service-providers/add/index';
import { Route as PrivateReservationsAddIndexRouteImport } from './routes/_private/reservations/add/index';
import { Route as PrivateDependentsAddIndexRouteImport } from './routes/_private/dependents/add/index';
import { Route as PublicAppAuthResetPasswordTokenRouteImport } from './routes/_public/app-auth/reset-password/$token';

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any);
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any);
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRoute,
} as any);
const PublicPrivacyPolicyIndexRoute =
  PublicPrivacyPolicyIndexRouteImport.update({
    id: '/privacy-policy/',
    path: '/privacy-policy/',
    getParentRoute: () => PublicRoute,
  } as any);
const PublicNewAccessIndexRoute = PublicNewAccessIndexRouteImport.update({
  id: '/new-access/',
  path: '/new-access/',
  getParentRoute: () => PublicRoute,
} as any);
const PublicForgotPasswordIndexRoute =
  PublicForgotPasswordIndexRouteImport.update({
    id: '/forgot-password/',
    path: '/forgot-password/',
    getParentRoute: () => PublicRoute,
  } as any);
const PublicDevelopIndexRoute = PublicDevelopIndexRouteImport.update({
  id: '/develop/',
  path: '/develop/',
  getParentRoute: () => PublicRoute,
} as any);
const PublicContactIndexRoute = PublicContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => PublicRoute,
} as any);
const PublicAppAuthIndexRoute = PublicAppAuthIndexRouteImport.update({
  id: '/app-auth/',
  path: '/app-auth/',
  getParentRoute: () => PublicRoute,
} as any);
const PrivateVisitorsIndexRoute = PrivateVisitorsIndexRouteImport.update({
  id: '/visitors/',
  path: '/visitors/',
  getParentRoute: () => PrivateRoute,
} as any);
const PrivateUnitsIndexRoute = PrivateUnitsIndexRouteImport.update({
  id: '/units/',
  path: '/units/',
  getParentRoute: () => PrivateRoute,
} as any);
const PrivateSyncStatusIndexRoute = PrivateSyncStatusIndexRouteImport.update({
  id: '/sync-status/',
  path: '/sync-status/',
  getParentRoute: () => PrivateRoute,
} as any);
const PrivateServiceProvidersIndexRoute =
  PrivateServiceProvidersIndexRouteImport.update({
    id: '/service-providers/',
    path: '/service-providers/',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivateReservationsIndexRoute =
  PrivateReservationsIndexRouteImport.update({
    id: '/reservations/',
    path: '/reservations/',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivateDependentsIndexRoute = PrivateDependentsIndexRouteImport.update({
  id: '/dependents/',
  path: '/dependents/',
  getParentRoute: () => PrivateRoute,
} as any);
const PrivateAccessUserIndexRoute = PrivateAccessUserIndexRouteImport.update({
  id: '/access-user/',
  path: '/access-user/',
  getParentRoute: () => PrivateRoute,
} as any);
const PublicNewUserIdRoute = PublicNewUserIdRouteImport.update({
  id: '/new-user/$id',
  path: '/new-user/$id',
  getParentRoute: () => PublicRoute,
} as any);
const PrivateReservationsDetailsRoute =
  PrivateReservationsDetailsRouteImport.update({
    id: '/reservations/details',
    path: '/reservations/details',
    getParentRoute: () => PrivateRoute,
  } as any);
const PublicAccomplishAccessIdIndexRoute =
  PublicAccomplishAccessIdIndexRouteImport.update({
    id: '/accomplish-access/$id/',
    path: '/accomplish-access/$id/',
    getParentRoute: () => PublicRoute,
  } as any);
const PrivateVisitorsAddIndexRoute = PrivateVisitorsAddIndexRouteImport.update({
  id: '/visitors/add/',
  path: '/visitors/add/',
  getParentRoute: () => PrivateRoute,
} as any);
const PrivateServiceProvidersAddIndexRoute =
  PrivateServiceProvidersAddIndexRouteImport.update({
    id: '/service-providers/add/',
    path: '/service-providers/add/',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivateReservationsAddIndexRoute =
  PrivateReservationsAddIndexRouteImport.update({
    id: '/reservations/add/',
    path: '/reservations/add/',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivateDependentsAddIndexRoute =
  PrivateDependentsAddIndexRouteImport.update({
    id: '/dependents/add/',
    path: '/dependents/add/',
    getParentRoute: () => PrivateRoute,
  } as any);
const PublicAppAuthResetPasswordTokenRoute =
  PublicAppAuthResetPasswordTokenRouteImport.update({
    id: '/app-auth/reset-password/$token',
    path: '/app-auth/reset-password/$token',
    getParentRoute: () => PublicRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof PrivateIndexRoute;
  '/reservations/details': typeof PrivateReservationsDetailsRoute;
  '/new-user/$id': typeof PublicNewUserIdRoute;
  '/access-user/': typeof PrivateAccessUserIndexRoute;
  '/dependents/': typeof PrivateDependentsIndexRoute;
  '/reservations/': typeof PrivateReservationsIndexRoute;
  '/service-providers/': typeof PrivateServiceProvidersIndexRoute;
  '/sync-status/': typeof PrivateSyncStatusIndexRoute;
  '/units/': typeof PrivateUnitsIndexRoute;
  '/visitors/': typeof PrivateVisitorsIndexRoute;
  '/app-auth/': typeof PublicAppAuthIndexRoute;
  '/contact/': typeof PublicContactIndexRoute;
  '/develop/': typeof PublicDevelopIndexRoute;
  '/forgot-password/': typeof PublicForgotPasswordIndexRoute;
  '/new-access/': typeof PublicNewAccessIndexRoute;
  '/privacy-policy/': typeof PublicPrivacyPolicyIndexRoute;
  '/app-auth/reset-password/$token': typeof PublicAppAuthResetPasswordTokenRoute;
  '/dependents/add/': typeof PrivateDependentsAddIndexRoute;
  '/reservations/add/': typeof PrivateReservationsAddIndexRoute;
  '/service-providers/add/': typeof PrivateServiceProvidersAddIndexRoute;
  '/visitors/add/': typeof PrivateVisitorsAddIndexRoute;
  '/accomplish-access/$id/': typeof PublicAccomplishAccessIdIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof PrivateIndexRoute;
  '/reservations/details': typeof PrivateReservationsDetailsRoute;
  '/new-user/$id': typeof PublicNewUserIdRoute;
  '/access-user': typeof PrivateAccessUserIndexRoute;
  '/dependents': typeof PrivateDependentsIndexRoute;
  '/reservations': typeof PrivateReservationsIndexRoute;
  '/service-providers': typeof PrivateServiceProvidersIndexRoute;
  '/sync-status': typeof PrivateSyncStatusIndexRoute;
  '/units': typeof PrivateUnitsIndexRoute;
  '/visitors': typeof PrivateVisitorsIndexRoute;
  '/app-auth': typeof PublicAppAuthIndexRoute;
  '/contact': typeof PublicContactIndexRoute;
  '/develop': typeof PublicDevelopIndexRoute;
  '/forgot-password': typeof PublicForgotPasswordIndexRoute;
  '/new-access': typeof PublicNewAccessIndexRoute;
  '/privacy-policy': typeof PublicPrivacyPolicyIndexRoute;
  '/app-auth/reset-password/$token': typeof PublicAppAuthResetPasswordTokenRoute;
  '/dependents/add': typeof PrivateDependentsAddIndexRoute;
  '/reservations/add': typeof PrivateReservationsAddIndexRoute;
  '/service-providers/add': typeof PrivateServiceProvidersAddIndexRoute;
  '/visitors/add': typeof PrivateVisitorsAddIndexRoute;
  '/accomplish-access/$id': typeof PublicAccomplishAccessIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_private': typeof PrivateRouteWithChildren;
  '/_public': typeof PublicRouteWithChildren;
  '/_private/': typeof PrivateIndexRoute;
  '/_private/reservations/details': typeof PrivateReservationsDetailsRoute;
  '/_public/new-user/$id': typeof PublicNewUserIdRoute;
  '/_private/access-user/': typeof PrivateAccessUserIndexRoute;
  '/_private/dependents/': typeof PrivateDependentsIndexRoute;
  '/_private/reservations/': typeof PrivateReservationsIndexRoute;
  '/_private/service-providers/': typeof PrivateServiceProvidersIndexRoute;
  '/_private/sync-status/': typeof PrivateSyncStatusIndexRoute;
  '/_private/units/': typeof PrivateUnitsIndexRoute;
  '/_private/visitors/': typeof PrivateVisitorsIndexRoute;
  '/_public/app-auth/': typeof PublicAppAuthIndexRoute;
  '/_public/contact/': typeof PublicContactIndexRoute;
  '/_public/develop/': typeof PublicDevelopIndexRoute;
  '/_public/forgot-password/': typeof PublicForgotPasswordIndexRoute;
  '/_public/new-access/': typeof PublicNewAccessIndexRoute;
  '/_public/privacy-policy/': typeof PublicPrivacyPolicyIndexRoute;
  '/_public/app-auth/reset-password/$token': typeof PublicAppAuthResetPasswordTokenRoute;
  '/_private/dependents/add/': typeof PrivateDependentsAddIndexRoute;
  '/_private/reservations/add/': typeof PrivateReservationsAddIndexRoute;
  '/_private/service-providers/add/': typeof PrivateServiceProvidersAddIndexRoute;
  '/_private/visitors/add/': typeof PrivateVisitorsAddIndexRoute;
  '/_public/accomplish-access/$id/': typeof PublicAccomplishAccessIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/reservations/details'
    | '/new-user/$id'
    | '/access-user/'
    | '/dependents/'
    | '/reservations/'
    | '/service-providers/'
    | '/sync-status/'
    | '/units/'
    | '/visitors/'
    | '/app-auth/'
    | '/contact/'
    | '/develop/'
    | '/forgot-password/'
    | '/new-access/'
    | '/privacy-policy/'
    | '/app-auth/reset-password/$token'
    | '/dependents/add/'
    | '/reservations/add/'
    | '/service-providers/add/'
    | '/visitors/add/'
    | '/accomplish-access/$id/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/reservations/details'
    | '/new-user/$id'
    | '/access-user'
    | '/dependents'
    | '/reservations'
    | '/service-providers'
    | '/sync-status'
    | '/units'
    | '/visitors'
    | '/app-auth'
    | '/contact'
    | '/develop'
    | '/forgot-password'
    | '/new-access'
    | '/privacy-policy'
    | '/app-auth/reset-password/$token'
    | '/dependents/add'
    | '/reservations/add'
    | '/service-providers/add'
    | '/visitors/add'
    | '/accomplish-access/$id';
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/_private/'
    | '/_private/reservations/details'
    | '/_public/new-user/$id'
    | '/_private/access-user/'
    | '/_private/dependents/'
    | '/_private/reservations/'
    | '/_private/service-providers/'
    | '/_private/sync-status/'
    | '/_private/units/'
    | '/_private/visitors/'
    | '/_public/app-auth/'
    | '/_public/contact/'
    | '/_public/develop/'
    | '/_public/forgot-password/'
    | '/_public/new-access/'
    | '/_public/privacy-policy/'
    | '/_public/app-auth/reset-password/$token'
    | '/_private/dependents/add/'
    | '/_private/reservations/add/'
    | '/_private/service-providers/add/'
    | '/_private/visitors/add/'
    | '/_public/accomplish-access/$id/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren;
  PublicRoute: typeof PublicRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof PublicRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_private': {
      id: '/_private';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof PrivateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_private/': {
      id: '/_private/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof PrivateIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_public/privacy-policy/': {
      id: '/_public/privacy-policy/';
      path: '/privacy-policy';
      fullPath: '/privacy-policy/';
      preLoaderRoute: typeof PublicPrivacyPolicyIndexRouteImport;
      parentRoute: typeof PublicRoute;
    };
    '/_public/new-access/': {
      id: '/_public/new-access/';
      path: '/new-access';
      fullPath: '/new-access/';
      preLoaderRoute: typeof PublicNewAccessIndexRouteImport;
      parentRoute: typeof PublicRoute;
    };
    '/_public/forgot-password/': {
      id: '/_public/forgot-password/';
      path: '/forgot-password';
      fullPath: '/forgot-password/';
      preLoaderRoute: typeof PublicForgotPasswordIndexRouteImport;
      parentRoute: typeof PublicRoute;
    };
    '/_public/develop/': {
      id: '/_public/develop/';
      path: '/develop';
      fullPath: '/develop/';
      preLoaderRoute: typeof PublicDevelopIndexRouteImport;
      parentRoute: typeof PublicRoute;
    };
    '/_public/contact/': {
      id: '/_public/contact/';
      path: '/contact';
      fullPath: '/contact/';
      preLoaderRoute: typeof PublicContactIndexRouteImport;
      parentRoute: typeof PublicRoute;
    };
    '/_public/app-auth/': {
      id: '/_public/app-auth/';
      path: '/app-auth';
      fullPath: '/app-auth/';
      preLoaderRoute: typeof PublicAppAuthIndexRouteImport;
      parentRoute: typeof PublicRoute;
    };
    '/_private/visitors/': {
      id: '/_private/visitors/';
      path: '/visitors';
      fullPath: '/visitors/';
      preLoaderRoute: typeof PrivateVisitorsIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/units/': {
      id: '/_private/units/';
      path: '/units';
      fullPath: '/units/';
      preLoaderRoute: typeof PrivateUnitsIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/sync-status/': {
      id: '/_private/sync-status/';
      path: '/sync-status';
      fullPath: '/sync-status/';
      preLoaderRoute: typeof PrivateSyncStatusIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/service-providers/': {
      id: '/_private/service-providers/';
      path: '/service-providers';
      fullPath: '/service-providers/';
      preLoaderRoute: typeof PrivateServiceProvidersIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/reservations/': {
      id: '/_private/reservations/';
      path: '/reservations';
      fullPath: '/reservations/';
      preLoaderRoute: typeof PrivateReservationsIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/dependents/': {
      id: '/_private/dependents/';
      path: '/dependents';
      fullPath: '/dependents/';
      preLoaderRoute: typeof PrivateDependentsIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/access-user/': {
      id: '/_private/access-user/';
      path: '/access-user';
      fullPath: '/access-user/';
      preLoaderRoute: typeof PrivateAccessUserIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_public/new-user/$id': {
      id: '/_public/new-user/$id';
      path: '/new-user/$id';
      fullPath: '/new-user/$id';
      preLoaderRoute: typeof PublicNewUserIdRouteImport;
      parentRoute: typeof PublicRoute;
    };
    '/_private/reservations/details': {
      id: '/_private/reservations/details';
      path: '/reservations/details';
      fullPath: '/reservations/details';
      preLoaderRoute: typeof PrivateReservationsDetailsRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_public/accomplish-access/$id/': {
      id: '/_public/accomplish-access/$id/';
      path: '/accomplish-access/$id';
      fullPath: '/accomplish-access/$id/';
      preLoaderRoute: typeof PublicAccomplishAccessIdIndexRouteImport;
      parentRoute: typeof PublicRoute;
    };
    '/_private/visitors/add/': {
      id: '/_private/visitors/add/';
      path: '/visitors/add';
      fullPath: '/visitors/add/';
      preLoaderRoute: typeof PrivateVisitorsAddIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/service-providers/add/': {
      id: '/_private/service-providers/add/';
      path: '/service-providers/add';
      fullPath: '/service-providers/add/';
      preLoaderRoute: typeof PrivateServiceProvidersAddIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/reservations/add/': {
      id: '/_private/reservations/add/';
      path: '/reservations/add';
      fullPath: '/reservations/add/';
      preLoaderRoute: typeof PrivateReservationsAddIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/dependents/add/': {
      id: '/_private/dependents/add/';
      path: '/dependents/add';
      fullPath: '/dependents/add/';
      preLoaderRoute: typeof PrivateDependentsAddIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_public/app-auth/reset-password/$token': {
      id: '/_public/app-auth/reset-password/$token';
      path: '/app-auth/reset-password/$token';
      fullPath: '/app-auth/reset-password/$token';
      preLoaderRoute: typeof PublicAppAuthResetPasswordTokenRouteImport;
      parentRoute: typeof PublicRoute;
    };
  }
}

interface PrivateRouteChildren {
  PrivateIndexRoute: typeof PrivateIndexRoute;
  PrivateReservationsDetailsRoute: typeof PrivateReservationsDetailsRoute;
  PrivateAccessUserIndexRoute: typeof PrivateAccessUserIndexRoute;
  PrivateDependentsIndexRoute: typeof PrivateDependentsIndexRoute;
  PrivateReservationsIndexRoute: typeof PrivateReservationsIndexRoute;
  PrivateServiceProvidersIndexRoute: typeof PrivateServiceProvidersIndexRoute;
  PrivateSyncStatusIndexRoute: typeof PrivateSyncStatusIndexRoute;
  PrivateUnitsIndexRoute: typeof PrivateUnitsIndexRoute;
  PrivateVisitorsIndexRoute: typeof PrivateVisitorsIndexRoute;
  PrivateDependentsAddIndexRoute: typeof PrivateDependentsAddIndexRoute;
  PrivateReservationsAddIndexRoute: typeof PrivateReservationsAddIndexRoute;
  PrivateServiceProvidersAddIndexRoute: typeof PrivateServiceProvidersAddIndexRoute;
  PrivateVisitorsAddIndexRoute: typeof PrivateVisitorsAddIndexRoute;
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateIndexRoute: PrivateIndexRoute,
  PrivateReservationsDetailsRoute: PrivateReservationsDetailsRoute,
  PrivateAccessUserIndexRoute: PrivateAccessUserIndexRoute,
  PrivateDependentsIndexRoute: PrivateDependentsIndexRoute,
  PrivateReservationsIndexRoute: PrivateReservationsIndexRoute,
  PrivateServiceProvidersIndexRoute: PrivateServiceProvidersIndexRoute,
  PrivateSyncStatusIndexRoute: PrivateSyncStatusIndexRoute,
  PrivateUnitsIndexRoute: PrivateUnitsIndexRoute,
  PrivateVisitorsIndexRoute: PrivateVisitorsIndexRoute,
  PrivateDependentsAddIndexRoute: PrivateDependentsAddIndexRoute,
  PrivateReservationsAddIndexRoute: PrivateReservationsAddIndexRoute,
  PrivateServiceProvidersAddIndexRoute: PrivateServiceProvidersAddIndexRoute,
  PrivateVisitorsAddIndexRoute: PrivateVisitorsAddIndexRoute,
};

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren);

interface PublicRouteChildren {
  PublicNewUserIdRoute: typeof PublicNewUserIdRoute;
  PublicAppAuthIndexRoute: typeof PublicAppAuthIndexRoute;
  PublicContactIndexRoute: typeof PublicContactIndexRoute;
  PublicDevelopIndexRoute: typeof PublicDevelopIndexRoute;
  PublicForgotPasswordIndexRoute: typeof PublicForgotPasswordIndexRoute;
  PublicNewAccessIndexRoute: typeof PublicNewAccessIndexRoute;
  PublicPrivacyPolicyIndexRoute: typeof PublicPrivacyPolicyIndexRoute;
  PublicAppAuthResetPasswordTokenRoute: typeof PublicAppAuthResetPasswordTokenRoute;
  PublicAccomplishAccessIdIndexRoute: typeof PublicAccomplishAccessIdIndexRoute;
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicNewUserIdRoute: PublicNewUserIdRoute,
  PublicAppAuthIndexRoute: PublicAppAuthIndexRoute,
  PublicContactIndexRoute: PublicContactIndexRoute,
  PublicDevelopIndexRoute: PublicDevelopIndexRoute,
  PublicForgotPasswordIndexRoute: PublicForgotPasswordIndexRoute,
  PublicNewAccessIndexRoute: PublicNewAccessIndexRoute,
  PublicPrivacyPolicyIndexRoute: PublicPrivacyPolicyIndexRoute,
  PublicAppAuthResetPasswordTokenRoute: PublicAppAuthResetPasswordTokenRoute,
  PublicAccomplishAccessIdIndexRoute: PublicAccomplishAccessIdIndexRoute,
};

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
